### ISSUE TITLE
Make_Regular removes GW Data

### ISSUE THREAD

**Issue by callumj2** [HydroGeoSines/HydroGeoSines#41]
Hi guys,

I was trying to get HGS running on some hourly sampled data, and ran into the following error traceback when using processor.fft functionality:

![image](https://user-images.githubusercontent.com/66106348/174224949-98ca26c6-019a-4321-8a18-9dfa32c35574.png)

After doing a little digging, it seems like when the hgs module runs 'make_regular' on itself it actually removes the groundwater data from the dataset. Part of this issue is likely me not fully understanding what's actually happening under the hood with this call.

If you would like to attempt to recreate this issue I have added the data used to this post.

Cheers guys!
[tobiah_adj.csv](https://github.com/HydroGeoSines/HydroGeoSines/files/8924534/tobiah_adj.csv)

**Comment by hydrogeoscience** [comment]
Thanks for raising this issue. It took me a while to figure out what was going on. In summary, the datetime stamps are inferred through Pandas' `read_csv()` function with `infer_datetime_format=True`. Because we mainly work outside the US, we also set `dayfirst=True`.

The date and time format in your CSV is given as _YYYY-mm-dd_. The above combination of flags leads to a confusion in translation, whereby months and days are mixed up. There is a good summary of the issue here: 
https://medium.com/@dvdpedros/avoid-this-shortcut-when-parsing-dates-in-pandas-a175bd39ec73

I have added the key `dayfirst ` to our `read_csv()` function which is forwarded to Pandas. Setting this to `False` solves the issue. However, HGS then returns a different error: `Exception: To use FFT, the duration must be >=60 days!`. This is a legitimate limitation caused y the fact that your dataset is too short for what you are trying to do.
